### ISSUE TITLE
Get masks using onnx and opencv

### ISSUE THREAD

**Issue by mucahitrtn** [zhangjinsong3/SOLOv2.tensorRT#16]
I have converted the trained `SOLOv2_R50_3x.pth` model into onnx model using this repository. I used the solov2_r50_fpn_8gpu_3x.py  config file and I'm trying to get masks using opencv. 

Here is how I convert trained pytorch model into onnx model.
```py 
python onnx_exporter_solov2.py   solov2_r50_fpn_8gpu_3x.py    SOLOv2_R50.onnx   --checkpoint SOLOv2_R50_3x.pth   --shape 256 256
```

Here is my onnx model. [Link](https://drive.google.com/file/d/1-0M0_RuPEzxmEJX7pIITKYFykg3I795v/view?usp=sharing)

Here is my code to read the network and get masks .

```py
import cv2
import numpy as np 

net = cv2.dnn.readNetFromONNX("SOLOv2_R50.onnx")

img = cv2.imread("elephant-symbolism6.jpg")

img = cv2.resize(img, (256,256))

blob = cv2.dnn.blobFromImage(img, swapRB=True)

net.setInput(blob)

cate_pred, kernel_pred, seg_pred = net.forward(['cate_pred', 'kernel_pred', 'seg_pred'])

```
Here is the size of this arrays.

```
cate_pred:    (3872, 80)
kernel_pred:  (3872, 256)
seg_pred:     (1,256,64,64)
```

This code runs without any errors but I'm not sure what are cate_pred, kernel_pred, seg_pred and what they represent. 

What are cate_pred, kernel_pred, seg_pred used for and how can I get masks with them?

**Comment by JaneLinlalala** [comment]
HI!
I also trying to convert the pth model into onnx model.
But I got this mistake:
Traceback (most recent call last):
  File "pth2onnx.py", line 33, in <module>
    torch.onnx.export(model, dummy_input, 'weights/solov2_r50_3x.onnx', input_names=input_names, output_names=output_names, verbose=True, opset_version=11)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/jit/__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/research/linjq/SOLOv2.tensorRT-main/mmdet/models/detectors/single_stage_ins.py", line 56, in forward_dummy
    x = self.extract_feat(img)
  File "/home/research/linjq/SOLOv2.tensorRT-main/mmdet/models/detectors/single_stage_ins.py", line 52, in extract_feat
    x = self.neck(x)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/research/miniconda3/envs/solov2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/research/linjq/SOLOv2.tensorRT-main/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/research/linjq/SOLOv2.tensorRT-main/mmdet/models/necks/fpn.py", line 122, in forward
    laterals[i], size=(size_h, size_w), mode='nearest')
RuntimeError: The size of tensor a (167) must match the size of tensor b (168) at non-singleton dimension 2

Have you met this?

**Comment by Sahil028** [comment]
@JaneLinlalala try installing tensorrt and pycuda and import them before running the onnx_exporter file. This solved the above error for me
